[package]
name = "projet"
version = "0.1.0"
authors = ["<Elias MESTOUR : elias.mestour@yahoo.com>, <Raphaël TEXEIRA : >, <Andy KADYAMBU : >"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
